import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';

const USE_MOCK = process.env.USE_MOCK_APIS === 'true';

// PDF Styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    paddingBottom: 10,
    borderBottom: '2 solid #0ea5e9',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#0c4a6e',
  },
  subtitle: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 10,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#0369a1',
    borderBottom: '1 solid #cbd5e1',
    paddingBottom: 5,
  },
  content: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#1e293b',
    marginBottom: 10,
  },
  providerHeader: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 8,
    color: '#0284c7',
  },
  metadata: {
    fontSize: 9,
    color: '#64748b',
    marginTop: 20,
    paddingTop: 10,
    borderTop: '1 solid #e2e8f0',
  },
});

interface PDFContentProps {
  title: string;
  initialPrompt: string;
  refinedPrompt?: string;
  openaiResult?: string;
  geminiResult?: string;
  createdAt: Date;
}

const PDFContent: React.FC<PDFContentProps> = ({
  title,
  initialPrompt,
  refinedPrompt,
  openaiResult,
  geminiResult,
  createdAt,
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>
          Generated on {createdAt.toLocaleDateString()} at {createdAt.toLocaleTimeString()}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Research Details</Text>
        <Text style={styles.content}>
          <Text style={{ fontWeight: 'bold' }}>Title:</Text> {title}
        </Text>
        <Text style={[styles.content, { marginTop: 8 }]}>
          <Text style={{ fontWeight: 'bold' }}>Initial Prompt:</Text> {initialPrompt}
        </Text>
        {refinedPrompt && refinedPrompt !== initialPrompt && (
          <Text style={[styles.content, { marginTop: 8 }]}>
            <Text style={{ fontWeight: 'bold' }}>Refined Prompt:</Text> {refinedPrompt}
          </Text>
        )}
      </View>

      {openaiResult && (
        <View style={styles.section}>
          <Text style={styles.providerHeader}>OpenAI Deep Research Results</Text>
          <Text style={styles.content}>{openaiResult}</Text>
        </View>
      )}

      {geminiResult && (
        <View style={styles.section}>
          <Text style={styles.providerHeader}>Google Gemini Research Results</Text>
          <Text style={styles.content}>{geminiResult}</Text>
        </View>
      )}

      <View style={styles.metadata}>
        <Text>
          This report was generated by the Multi-API Deep Research Assistant, combining insights
          from OpenAI and Google Gemini.
        </Text>
      </View>
    </Page>
  </Document>
);

/**
 * Generate PDF buffer from research results
 */
export async function generatePDFBuffer(
  title: string,
  initialPrompt: string,
  refinedPrompt: string | undefined,
  openaiResult: string | undefined,
  geminiResult: string | undefined,
  createdAt: Date
): Promise<Buffer> {
  try {
    const doc = (
      <PDFContent
        title={title}
        initialPrompt={initialPrompt}
        refinedPrompt={refinedPrompt}
        openaiResult={openaiResult || 'No OpenAI result available'}
        geminiResult={geminiResult || 'No Gemini result available'}
        createdAt={createdAt}
      />
    );

    // Generate PDF - @react-pdf/renderer works in Node.js
    // Use renderToBuffer for server-side rendering (returns a Promise<Buffer>)
    const buffer = await renderToBuffer(doc);
    return buffer;
  } catch (error: any) {
    console.error('PDF generation error:', error);
    throw new Error(`PDF generation error: ${error.message}`);
  }
}

/**
 * Generate PDF and return as base64 string
 */
export async function generatePDFBase64(
  title: string,
  initialPrompt: string,
  refinedPrompt: string | undefined,
  openaiResult: string | undefined,
  geminiResult: string | undefined,
  createdAt: Date
): Promise<string> {
  const buffer = await generatePDFBuffer(
    title,
    initialPrompt,
    refinedPrompt,
    openaiResult,
    geminiResult,
    createdAt
  );
  return buffer.toString('base64');
}


